name: Run commands on different operating systems
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Run-npm-on-Ubuntu:
    name: Run npm on Ubuntu
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - name: File check
        run: |
          node --version
          which node
          ls -la /usr/local/bin/node
          ls -la /usr/local/bin/node*
          find / -name node 
          echo ${{ hashFiles('README.md') }}
