name: Run commands on different operating systems
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Run-npm-on-Ubuntu:
    name: Run npm on Ubuntu
    runs-on: ubuntu-26.04
    steps:
      - uses: actions/checkout@v6
      - name: File check
        run: |
          ls -la
          echo ${{ hashFiles('README.md') }}
