name: hasher
on:
  workflow_dispatch:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: runner
    steps:
      # - uses: actions/cache@v4
      #   with:
      #     path: ~/.cache
      #     key: ${{ hashFiles('README.md') }}
      #     restore-keys: |
      #       ${{ hashFiles('README.md') }}
      - uses: actions/checkout@v6
      
      - name: File check
        run: |
          ls -la
          echo ${{ hashFiles('README.md') }}
